export const ADD_CATEGORY_STARTED = 'ADD_CATEGORY_STARTED';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const ADD_MONEY_SUCCESS = 'ADD_MONEY_SUCCESS';
export const ADD_MONEY_FAILURE = 'ADD_MONEY_FAILURE';
export const ADD_MONEY_STARTED = 'ADD_MONEY_STARTED';

export const DELETE_CATEGORY_STARTED = 'DELETE_CATEGORY_STARTED';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const RENAME_CATEGORY_SUCCESS = 'RENAME_CATEGORY_SUCCESS';
export const RENAME_CATEGORY_FAILURE = 'RENAME_CATEGORY_FAILURE';
export const RENAME_CATEGORY_STARTED = 'RENAME_CATEGORY_STARTED';

export const GET_USER_INFO_STARTED = 'GET_USER_INFO_STARTED';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';

export const MODAL_OPENED = 'MODAL_OPENED';
export const MODAL_CLOSED = 'MODAL_CLOSED';
