export const ADD_CATEGORY_STARTED = 'ADD_CATEGORY_STARTED';
export const ADD_CATEGORY_FAILURE = 'ADD_CATEGORY_FAILURE';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const ADD_MONEY_SUCCESS = 'ADD_MONEY_SUCCESS';
export const ADD_MONEY_FAILURE = 'ADD_MONEY_FAILURE';
export const ADD_MONEY_STARTED = 'ADD_MONEY_STARTED';

export const DELETE_CATEGORY_STARTED = 'DELETE_CATEGORY_STARTED';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const RENAME_CATEGORY_SUCCESS = 'RENAME_CATEGORY_SUCCESS';
export const RENAME_CATEGORY_FAILURE = 'RENAME_CATEGORY_FAILURE';
export const RENAME_CATEGORY_STARTED = 'RENAME_CATEGORY_STARTED';

export const SET_USER_INFO_STARTED = 'SET_USER_INFO_STARTED';
export const SET_USER_INFO_SUCCESS = 'SET_USER_INFO_SUCCESS';
export const SET_USER_INFO_FAILURE = 'SET_USER_INFO_FAILURE';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';

export const MODAL_OPENED = 'MODAL_OPENED';
export const MODAL_CLOSED = 'MODAL_CLOSED';

export const MODAL_ADD_CATEGORY_OPENED = 'MODAL_ADD_CATEGORY_OPENED';
export const MODAL_ADD_CATEGORY_CLOSED = 'MODAL_ADD_CATEGORY_CLOSED';

export const MODAL_TRANSFER_MONEY_OPENED = 'MODAL_TRANSFER_MONEY_OPENED';
export const MODAL_TRANSFER_MONEY_CLOSED = 'MODAL_TRANSFER_MONEY_CLOSED';

export const ADD_MONEY_STORE_STARTED = 'ADD_MONEY_STORE_STARTED';
export const ADD_MONEY_STORE_SUCCESS = 'ADD_MONEY_STORE_SUCCESS';
export const ADD_MONEY_STORE_FAILURE = 'ADD_MONEY_STORE_FAILURE';

export const TRANSFER_MONEY_STORE_STARTED = 'TRANSFER_MONEY_STORE_STARTED';
export const TRANSFER_MONEY_STORE_SUCCESS = 'TRANSFER_MONEY_STORE_SUCCESS';
export const TRANSFER_MONEY_STORE_FAILURE = 'TRANSFER_MONEY_STORE_FAILURE';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const ADD_TRANSACTION = 'ADD_TRANSACTION';

export const MODAL_TRANSACTION_HISTORY_OPENED =
  'MODAL_TRANSACTION_HISTORY_OPENED';
export const MODAL_TRANSACTION_HISTORY_CLOSED =
  'MODAL_TRANSACTION_HISTORY_CLOSED';

export const DELETE_TRANSACTION_STARTED = 'DELETE_TRANSACTION_STARTED';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
